name: Deploy Docker Image

on:
  push:
    branches: [ "main" ]
  schedule:
    # Everyday 8am
    - cron: "0 8 * * *"
jobs:

  docker-built-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        context: ["ros-noetic", "ubuntu-focal", "ubuntu-noble"]

    permissions:
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to ghcr.io
      uses: docker/login-action@v3
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io

    - name: Build the Docker image
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64, linux/arm64
        context: docker/${{ matrix.context }}
        push: true
        tags: ghcr.io/garaemon/${{ matrix.context }}:latest
