name: Deploy Docker Image

on:
  push:
    branches: [ "main" ]

jobs:

  deploy-ros-noetic-docker:
    runs-on: ubuntu-latest
    permissions:
      # contents: read
      packages: write
      # attestations: write
      # id-token: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to ghcr.io
      uses: docker/login-action@v3
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io

    - name: Build the Docker image
      uses: docker/build-push-action@v6
      with:
        context: docker/ros-noetic
        push: true
        tags: ghcr.io/garaemon/ros-noetic:latest

  deploy-ubuntu-focal:
    runs-on: ubuntu-latest
    permissions:
      # contents: read
      packages: write
      # attestations: write
      # id-token: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to ghcr.io
      uses: docker/login-action@v3
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io

    - name: Build the Docker image
      uses: docker/build-push-action@v6
      with:
        context: docker/ubuntu-focal
        push: true
        tags: ghcr.io/garaemon/ubuntu-focal:latest
