name: Test Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:

  docker-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        context: ["ros-noetic", "ubuntu-focal", "ubuntu-noble"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build the Docker image
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64, linux/arm64
        context: docker/${{ matrix.context }}
        push: false
